import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckCircle, Route, Bot, CalendarCheck } from "lucide-react";
import Link from "next/link";

export default function Home() {
  return (
    <div className="flex-1 w-full gradient-bg">
      <section className="w-full py-20 md:py-32 lg:py-40">
        <div className="container px-4 md:px-6 text-center">
          <div className="max-w-3xl mx-auto space-y-4">
            <h1 className="font-headline text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl text-foreground">
              Find Your Perfect Career Path with AI
            </h1>
            <p className="text-lg text-muted-foreground md:text-xl">
              Personalized career roadmaps and daily learning tasks powered by Google Gemini to help you achieve your professional goals.
            </p>
            <div className="flex flex-col gap-2 min-[400px]:flex-row justify-center">
              <Button asChild size="lg" className="font-semibold">
                <Link href="/ai-agent">Talk to AI Agent</Link>
              </Button>
              <Button asChild size="lg" variant="secondary" className="font-semibold">
                <Link href="/dashboard">View Dashboard</Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      <section className="w-full pb-20 md:pb-32 lg:pb-40 bg-card/50">
        <div className="container px-4 md:px-6">
          <div className="mx-auto grid max-w-5xl items-center gap-6 lg:grid-cols-3 lg:gap-12">
            <div className="lg:col-span-3 text-center space-y-2 mb-8">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl font-headline">Features to Guide Your Journey</h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed mx-auto">
                Everything you need to navigate your career path with confidence.
              </p>
            </div>
            
            <Card className="shadow-md hover:shadow-lg transition-shadow">
              <CardHeader className="flex flex-row items-center gap-4">
                <Route className="w-8 h-8 text-primary" />
                <CardTitle className="font-headline">AI Career Roadmaps</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">Get a step-by-step, personalized career plan generated by our advanced AI, tailored to your ambitions.</p>
              </CardContent>
            </Card>

            <Card className="shadow-md hover:shadow-lg transition-shadow">
              <CardHeader className="flex flex-row items-center gap-4">
                <CalendarCheck className="w-8 h-8 text-primary" />
                <CardTitle className="font-headline">Daily Learning Tasks</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">Receive daily, manageable tasks to build skills consistently and stay on track with your career goals.</p>
              </CardContent>
            </Card>

            <Card className="shadow-md hover:shadow-lg transition-shadow">
              <CardHeader className="flex flex-row items-center gap-4">
                <CheckCircle className="w-8 h-8 text-primary" />
                <CardTitle className="font-headline">Progress Tracking</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">Visualize your journey, track completed tasks, and monitor your skill development with our dashboard.</p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </div>
  );
}
